### PR TITLE
Updated local notification version.

### PR DESCRIPTION
**Pull request by eschlange**
* Updated and locked local notification cordova plugin.

[#110502010]

### CODE REVIEW

**Comment by eschlange** [comment]
@ericcf Hi Eric, I updated the localNotification Cordova plugin using the method that you describe in: https://github.com/NU-CBITS/guides/tree/master/development/cordova. The only updates to the project that I made were to the package.json and the config.xml file with the version numbers. All other changes are the changes to the plugin files that were automatically pulled in upon build.

**Comment by ericcf** [comment]
@eschlange looks like `config.xml` is not included in this commit?

**Comment by eschlange** [comment]
@ericcf I added the generated statement to the "config" template. Thanks!

**Comment by ericcf** [comment]
:tada:

**Pull request merged**
